### ISSUE TITLE
The plugin does not work!

### ISSUE THREAD

**Issue by DMZakaria** [Heyzap/heyzap-cordova-applovin#1]
Hello;
The plugin does not work, everything is green in my Tests Suite (SDK, Permissions,....)  but when I do my tests, the ads are not shown.

I did a quick debug with ADB and I got this error: 

```
java.lang.NoSuchMethodError: com.applovin.adview.AppLovinAdView.<init>
E/Heyzap  (22777):      at com.heyzap.sdk.mediation.adapter.ApplovinAdapter$AppLovinCachedBannerAd$1.run(ApplovinAdapter.java:467)
E/Heyzap  (22777):      at com.heyzap.common.concurrency.WrappedRunnable.run(WrappedRunnable.java:26)
E/Heyzap  (22777):      at com.heyzap.common.concurrency.HandlerExecutorService$2.run(HandlerExecutorService.java:59)
E/Heyzap  (22777):      at android.os.Handler.handleCallback(Handler.java:730)
E/Heyzap  (22777):      at android.os.Handler.dispatchMessage(Handler.java:92)
E/Heyzap  (22777):      at android.os.Looper.loop(Looper.java:176)
E/Heyzap  (22777):      at android.app.ActivityThread.main(ActivityThread.java:5419)
E/Heyzap  (22777):      at java.lang.reflect.Method.invokeNative(Native Method)
E/Heyzap  (22777):      at java.lang.reflect.Method.invoke(Method.java:525)
E/Heyzap  (22777):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
E/Heyzap  (22777):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
E/Heyzap  (22777):      at dalvik.system.NativeStart.main(Native Method)
```

It seems that a method is missing, Could you elaborate more on it? 
Thank you

**Comment by ccorcos** [comment]
Same here.

```
Heyzap has encountered an error and is shutting down.
java.lang.NoSuchMethodError: No direct method <init>(Lcom/applovin/sdk/AppLovinSdk;Lcom/applovin/sdk/AppLovinAdSize;Landroid/content/Context;)V in class Lcom/applovin/adview/AppLovinAdView; or its super classes (declaration of 'com.applovin.adview.AppLovinAdView' appears in /data/app/chetball.id-O5gCr-ysTkIWbxE7HEdfmg==/split_lib_dependencies_apk.apk)
		at com.heyzap.sdk.mediation.adapter.ApplovinAdapter$AppLovinCachedBannerAd$1.run(ApplovinAdapter.java:467)
		at com.heyzap.common.concurrency.WrappedRunnable.run(WrappedRunnable.java:26)
		at com.heyzap.common.concurrency.HandlerExecutorService$2.run(HandlerExecutorService.java:59)
		at android.os.Handler.handleCallback(Handler.java:790)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loop(Looper.java:164)
		at android.app.ActivityThread.main(ActivityThread.java:6494)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by ezpuzz** [comment]
Please try `cordova plugin add https://github.com/Heyzap/heyzap-cordova-applovin.git` I've updated the head to applovin sdk 7.3.2
